version: 2.1

orbs:
  line: decoch/line@1.0.0

references:
  working_dir: &working_dir /home/circleci/repo

  container_for_ruby: &container_for_ruby
    docker:
      - image: circleci/ruby:2.7.1
    working_directory: *working_dir

jobs:
  integration:
    <<: *container_for_ruby
    steps:
      - checkout
      - run:
          name: execute
          command: |
            ruby main.rb
      - line/notify:
          message: KanbanFlow2Toggl success

workflows:
  main:
    triggers:
      - schedule:
          cron: "0 9 * * *" # UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - integration
  test:
    jobs:
      - integration
